### PR TITLE
fix: set cookie max age

### LINKED ISSUE #34: Each session, the cookie expires; we need to establish a maximum age.
https://developer.chrome.com/blog/cookie-max-age-expires

If its unspecified, the cookie becomes a session cookie. A session finishes when the client shuts down, after which the session cookie is removed.

Many web browsers have a session restore feature that will save all tabs and restore them the next time the browser is used. Session cookies will also be restored, as if the browser was never closed.

But in our case we need to set max-age

### PR DESCRIPTION
**Pull request by nikhilverma360**
closes #34

### CODE REVIEW

File: src/app/api/auth/route.ts [hunk 1]
```diff
@@ -50,7 +50,10 @@ export const POST = async (request: NextRequest) => {
   };
 
   const response = new NextResponse(JSON.stringify(responseBody));
-  response.headers.set("Set-Cookie", `token=${token}; HttpOnly; Path=/`);
+  response.headers.set(
+    "Set-Cookie",
+    `token=${token}; HttpOnly; Path=/; Max-Age=31536000`
```
Comment (nikhilverma360) [inline src/app/api/auth/route.ts]: Max-Age = 1 year
